language: c++

before_install:
  - sudo dpkg --add-architecture i386
  - sudo apt-get -qq update

addons:
    apt:
        sources:
            - llvm-toolchain-precise
            - ubuntu-toolchain-r-test
        packages:
            - clang-3.7
            - g++-5
            - gcc-5
            - libsdl2-ttf-dev
            - libsdl2-dev
            - libboost-all-dev
script:
  - mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Debug ../source && cmake --build .

