language: c++

os:
    - linux

distro: precise

addons:
    apt:
        sources:
            - llvm-toolchain-precise-3.6
            - ubuntu-toolchain-r-test
        packages:
            - clang-3.6
              #            - g++-5
              #            - gcc-5
            - libboost-dev
            - libboost-program-options-dev
            - libboost-system-dev
            - libsdl2-dev
            - libsdl2-ttf-dev
script:
  - mkdir build && cd build && cmake -DCMAKE_CXX_COMPILER=clang++-3.6 -DCMAKE_BUILD_TYPE=Debug ../source && cmake --build .

